services:
  locust-master:
    image: locustio/locust:2.20.0
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:8080

  locust-worker:
    image: locustio/locust:2.20.0
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    deploy:
      replicas: 4
